"""Initial

Revision ID: deb02ea9facb
Revises: 
Create Date: 2023-02-04 11:58:51.582266

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'deb02ea9facb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('author', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('seek', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], name='fk_clips_guilds_id_guild'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'guild', name='uc_clips_name_guild')
    )
    op.create_table('punishment_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], name='fk_punishment_config_guilds_id_guild'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild')
    )
    op.create_table('punishment_songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], name='fk_punishment_songs_guilds_id_guild'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'guild', name='uc_punishment_songs_name_guild')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('punishment_songs')
    op.drop_table('punishment_config')
    op.drop_table('clips')
    op.drop_table('guilds')
    # ### end Alembic commands ###
