"""Drop clips table

Revision ID: ba07c4b9f095
Revises: deb02ea9facb
Create Date: 2024-03-23 14:55:15.348684

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ba07c4b9f095'
down_revision = 'deb02ea9facb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clips')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clips',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('guild', sa.BIGINT(), nullable=True),
    sa.Column('author', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('seek', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], name='fk_clips_guilds_id_guild'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'guild', name='uc_clips_name_guild')
    )
    # ### end Alembic commands ###
